In [ ]:
import numpy as np

In [ ]:
#task 1

In [ ]:
A = np.matrix([[1, 2, 1], [-2, 1, 1]])
print ("This is matrix A:\n", A)

This is matrix A:
 [[ 1  2  1]
 [-2  1  1]]


In [ ]:
B = np.matrix([[3, 1], [-1, 0], [2, 4]])
print ("This is matrix B:\n", B)

This is matrix B:
 [[ 3  1]
 [-1  0]
 [ 2  4]]


In [ ]:
C = np.matrix([[-2, 2], [1, -1], [1, 2]])
print ("This is matrix C:\n", C)

This is matrix C:
 [[-2  2]
 [ 1 -1]
 [ 1  2]]


In [ ]:
res1 = A.transpose() + B.dot(2)
print(res1)

[[7 0]
 [0 1]
 [5 9]]


In [ ]:
res2 = B + C.dot(2)
print(res2)

[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [ ]:
#task 2

In [ ]:
matrix = np.zeros((8,8))
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#task 3

In [ ]:
vector1 = np.arange(0, 1.5, 0.1)
print(vector1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]


In [ ]:
vector2 = np.arange(1, 7, 1)
print(vector2)

[1 2 3 4 5 6]


In [ ]:
matrix1 = vector1.reshape(5,3)
print(matrix1)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]


In [ ]:
matrix2 = vector2.reshape(3,2)
print(matrix2)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
result = matrix1.dot(matrix2)
print(result)

[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [ ]:
#task 4

In [ ]:
vector3 = np.arange(1, 73, 2, dtype=np.int32)
print(vector3)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]


In [ ]:
vector4 = vector3[vector3 % 3 == 0]
print(vector4)

[ 3  9 15 21 27 33 39 45 51 57 63 69]
